[template]
 src = "myconfig.conf.tmpl"
 dest = "/tmp/myconfig.conf"
 keys = [
     "/istio-system/istio-egressgateway",
     "/default/reviews",
     "/default/ratings",
     "/istio-system/istio-ingressgateway",
     "/istio-system/grafana",
 ]
 check_cmd = "/usr/sbin/nginx -t -c  /etc/nginx/nginx.conf"
 reload_cmd = "/usr/sbin/nginx -s  reload"